title: Manto Šimkūno tinklaraštis
baseurl: ""
url: "https://msimkunas.lt"
linkedin_username: msimkunas
github_username: msimkunas
facebook_username: simkunas.mantas

theme: minima
plugins:
    - jekyll-feed

minima:
    date_format: "%Y-%m-%d"

show_excerpts: false

lang: lt-LT

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - .bundle/
    - Gemfile
    - Gemfile.lock
    - CNAME
    - Dockerfile
    - docker-compose.yml
    - down.sh
    - up.sh
